# dce.rs::naive_dce_pass

benchmarks = '../tests/dce/*.bril'

# how to extract the performance metric from stderr
extract = 'total_dyn_inst: (\d+)'

[runs.baseline]
pipeline = [
  "bril2json",
  "brili -p",
]

[runs.local_dce]
pipeline = [
  "bril2json",
  "bril_forge local_dce_pass",
  "brili -p",
]
